from tkinter import *
root = Tk() 
root.option_add("*Font", "Fixedsys 20")
Label(root, text="Ford").pack(anchor=E)
Label(root, text="BMW", fg="blue").pack()
Label(root, text="Mercedes Benz", bg="yellow").pack(anchor="e")
Label(root, text="Audi", fg="green").pack(pady=10) 
Label(root, text="Toyota", bg="red", width=15).pack() 
Label(root, text="Honda", bg="gold").pack(fill=X)
Label(root, text="Nissan", fg="black", bg="purple").pack()
Label(root, text="Porsche", bg="pink").pack(fill=X)
Label(root, text="Kitsapong Maunkwan --- Kitsapong Maunkwan --- Kitsapong Maunkwan --- Kitsapong Maunkwan --- Kitsapong Maunkwan --- Kitsapong Maunkwan ---",bg="green").pack(fill=X)
Label(root, text="To awaken quite alone in a strange town is one of the pleasantest sensations in the world Half the fun of the travel is the esthetic of lostness.", bg="gray", wraplength=400).pack(fill=X)
root.mainloop()
